# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "yquake2-128"
languages = ["C"]
cmake-after = """
# Operating system.
set(YQ2OSTYPE "${CMAKE_SYSTEM_NAME}" CACHE STRING "Override operation system type")
add_definitions(-DYQ2OSTYPE="${YQ2OSTYPE}")
"""

[vcpkg]
version = "2023.11.20"
packages = ["sdl2"]

[find-package]
SDL2 = {}

# TODO: define a target for each of your executables/libraries like this:
#[target.myexecutable]
#type = "executable" # static, shared
#sources = ["src/yquake2-128/*.cpp", "include/yquake2-128/*.hpp"]
#include-directories = ["include"]
#compile-features = ["cxx_std_11"]
#link-libraries = ["target-or-library"]

# [target.backend]
# type = "static"
# sources = ["src/backends/generic/*.c"]
# windows.sources = ["src/backends/windows/icon.rc", "src/backends/windows/**.c", "src/backends/windows/**.h"]

[target.common]
type = "static"
sources = [
    "src/common/**.c",
    "src/common/**.h",
]

[target.game]
type = "static"
sources = [
    # "src/common/shared/flash.c",
    # "src/common/shared/rand.c",
    # "src/common/shared/shared.c",
    "src/game/**.c",
    "src/game/**.h",
]

[target.client]
type = "static"
sources = [
    "src/client/cl_cin.c",
	"src/client/cl_console.c",
	"src/client/cl_download.c",
	"src/client/cl_effects.c",
	"src/client/cl_entities.c",
	"src/client/cl_input.c",
	"src/client/cl_inventory.c",
	"src/client/cl_keyboard.c",
	"src/client/cl_lights.c",
	"src/client/cl_main.c",
	"src/client/cl_network.c",
	"src/client/cl_parse.c",
	"src/client/cl_particles.c",
	"src/client/cl_prediction.c",
	"src/client/cl_screen.c",
	"src/client/cl_tempentities.c",
	"src/client/cl_view.c",
	"src/client/curl/download.c",
	"src/client/curl/qcurl.c",
	"src/client/input/sdl.c",
	"src/client/menu/menu.c",
	"src/client/menu/qmenu.c",
	"src/client/menu/videomenu.c",
	"src/client/sound/ogg.c",
	"src/client/sound/openal.c",
	"src/client/sound/qal.c",
	"src/client/sound/sdl.c",
	"src/client/sound/sound.c",
	"src/client/sound/wave.c",
	"src/client/vid/glimp_sdl.c",
	"src/client/vid/vid.c",
    "src/client/**.h",
    # Other shit
    # "src/common/argproc.c",
    # "src/common/clientserver.c",
    # "src/common/collision.c",
    # "src/common/crc.c",
    # "src/common/cmdparser.c",
    # "src/common/cvar.c",
    # "src/common/filesystem.c",
    # "src/common/glob.c",
    # "src/common/md4.c",
    # "src/common/movemsg.c",
    # "src/common/frame.c",
    # "src/common/netchan.c",
    # "src/common/pmove.c",
    # "src/common/szone.c",
    # "src/common/zone.c",
    # "src/common/shared/flash.c",
    # "src/common/shared/rand.c",
    # "src/common/shared/shared.c",
    # "src/common/unzip/ioapi.c",
    # "src/common/unzip/unzip.c",
    # "src/common/unzip/miniz/miniz.c",
    # "src/common/unzip/miniz/miniz_tdef.c",
    # "src/common/unzip/miniz/miniz_tinfl.c",
    "src/server/sv_cmd.c",
	"src/server/sv_conless.c",
	"src/server/sv_entities.c",
	"src/server/sv_game.c",
	"src/server/sv_init.c",
	"src/server/sv_main.c",
	"src/server/sv_save.c",
	"src/server/sv_send.c",
	"src/server/sv_user.c",
	"src/server/sv_world.c",
    # headers
    "src/common/header/common.h",
	"src/common/header/crc.h",
	"src/common/header/files.h",
	"src/common/header/glob.h",
	"src/common/header/shared.h",
	"src/common/header/zone.h",
	"src/common/unzip/ioapi.h",
	"src/common/unzip/unzip.h",
	"src/common/unzip/miniz/miniz.h",
	"src/common/unzip/miniz/miniz_tdef.h",
	"src/common/unzip/miniz/miniz_tinfl.h",
	"src/common/unzip/miniz/minizconf.h",
	"src/server/header/server.h",
]
link-libraries = ["SDL2::SDL2"]

[target.server]
type = "static"
sources = [
    # "src/common/argproc.c",
	# "src/common/clientserver.c",
	# "src/common/collision.c",
	# "src/common/crc.c",
	# "src/common/cmdparser.c",
	# "src/common/cvar.c",
	# "src/common/filesystem.c",
	# "src/common/glob.c",
	# "src/common/md4.c",
	# "src/common/frame.c",
	# "src/common/movemsg.c",
	# "src/common/netchan.c",
	# "src/common/pmove.c",
	# "src/common/szone.c",
	# "src/common/zone.c",
	# "src/common/shared/rand.c",
	# "src/common/shared/shared.c",
	# "src/common/unzip/ioapi.c",
	# "src/common/unzip/unzip.c",
	# "src/common/unzip/miniz/miniz.c",
	# "src/common/unzip/miniz/miniz_tdef.c",
	# "src/common/unzip/miniz/miniz_tinfl.c",
    "src/common/header/common.h",
	"src/common/header/crc.h",
	"src/common/header/files.h",
	"src/common/header/glob.h",
	"src/common/header/shared.h",
	"src/common/header/zone.h",
	"src/common/unzip/ioapi.h",
	"src/common/unzip/unzip.h",
	"src/common/unzip/miniz/miniz.h",
	"src/common/unzip/miniz/miniz_tdef.h",
	"src/common/unzip/miniz/miniz_tinfl.h",
	"src/common/unzip/miniz/minizconf.h",
    # main server shit
    "src/server/**.c",
    "src/server/**.h",
]

[target.refresh-soft]
type = "static"
sources = [
    "src/client/refresh/soft/sw_aclip.c",
	"src/client/refresh/soft/sw_alias.c",
	"src/client/refresh/soft/sw_bsp.c",
	"src/client/refresh/soft/sw_draw.c",
	"src/client/refresh/soft/sw_edge.c",
	"src/client/refresh/soft/sw_image.c",
	"src/client/refresh/soft/sw_light.c",
	"src/client/refresh/soft/sw_main.c",
	"src/client/refresh/soft/sw_misc.c",
	"src/client/refresh/soft/sw_model.c",
	"src/client/refresh/soft/sw_part.c",
	"src/client/refresh/soft/sw_poly.c",
	"src/client/refresh/soft/sw_polyset.c",
	"src/client/refresh/soft/sw_rast.c",
	"src/client/refresh/soft/sw_scan.c",
	"src/client/refresh/soft/sw_sprite.c",
	"src/client/refresh/soft/sw_surf.c",
	"src/client/refresh/files/models.c",
	"src/client/refresh/files/pcx.c",
	"src/client/refresh/files/stb.c",
	"src/client/refresh/files/surf.c",
	"src/client/refresh/files/wal.c",
	"src/client/refresh/files/pvs.c",
	# "src/common/shared/shared.c",
	# "src/common/md4.c",

    "src/client/refresh/ref_shared.h",
	"src/client/refresh/files/stb_image.h",
	"src/client/refresh/files/stb_image_resize.h",
	"src/client/refresh/soft/header/local.h",
	"src/client/refresh/soft/header/model.h",
	"src/common/header/shared.h",
]
link-libraries = ["SDL2::SDL2"]

[target.yq2-128]
type = "executable"
sources = ["src/backends/generic/*.c"]
windows.sources = ["src/backends/windows/icon.rc", "src/backends/windows/**.c", "src/backends/windows/**.h"]
link-libraries = ["common", "game", "client", "refresh-soft", "SDL2::SDL2main"]
windows.link-libraries = ["ws2_32", "winmm"]